### ISSUE TITLE
Question: running x11 apps

### ISSUE THREAD

**Issue by peter1000** [sgotti/baci#2]
hi @sgotti,

I just came across `baci/ App Container/rocket` and have a question: with docker I used to run graphical apps like firefox.

e.g http://www.slideshare.net/dotCloud/dockerizing-your-appli

```
 docker run -e DISPLAY=unix$DISPLAY -volumes-from firefox-data -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/snd:/dev/snd -lxc-conf='lxc.cgroup.devices.allow = c 116:* rwm' firefox
```

e.g. https://registry.hub.docker.com/u/kennethkl/firefox/

```
docker run -d --name firefox -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix kennethkl/firefox
```

e.g. https://github.com/subuser-security/subuser

Do you know if something similar is possible with baci/ App Container/rocket.

Thanks
P

**Comment by sgotti** [comment]
@peter1000 sorry for the late answer.

This is probably more related to https://github.com/appc/spec and https://github.com/coreos/rkt.
You can just use `rkt fetch docker://kennethkl/firefox` to automatically fetch and convert a docker image to an ACI without rebuilding it using baci.

The execute X11 apps there's the need to bind mount the x11 socket files. See appc/spec#144.

Additionally, the appc/spec mandates that all the needed volumes should be defined in the image manifest while docker will let you define additional volumes at `docker run` time. So, if the `/tmp/.X11-unix` "volume" isn't provided in the DockerFile I can see two possible solutions:
- Use external tools to patch the image manifest (like `actool patch-manifest`)
- If you are going to build the image from a Docker files, an option to baci to define additional volumes (that will be added to the manifest) over the one provided by the Dockerfile and the parent image will be useful.

I haven't had time to try all of this so there can be probably other things that needs to be fixed.

**Comment by peter1000** [comment]
@sgotti thanks for write back.
